FROM quay.io/llamaland/base:latest
ARG CACHE_EPOCH

RUN dnf update --refresh -y && dnf install -y vulkan-tools && dnf clean all
ADD run.sh /usr/local/bin/run.sh
RUN mkdir /work; chmod a+rwx /work
WORKDIR /work

ENTRYPOINT ["/usr/local/bin/run.sh"]