FROM quay.io/llamaland/base:latest
ARG CACHE_EPOCH
LABEL maintainer="Wim Vander Schelden <lists@fixnum.org>"

RUN dnf install -y git cmake llvm clang vulkan-headers vulkan-loader-devel glslc curl-devel && dnf clean all
WORKDIR /build
RUN cd /build