name: Build and publish containers
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY_USER: llamaland+github_actions 
  IMAGE_REGISTRY: quay.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ${{ env.IMAGE_REGISTRY }}
        uses: docker/login-action@v3
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the images
      run: make containers

  publish:
    runs-on: ubuntu-latest
    needs: [login, build]
    steps:
    - name: Publish the images
      run: make publish-containers
