name: Run go tests
on:
  push:
    branches: [ "master", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Get dependencies
        run: go get -u ./..
      - name: Run tests
        run: go test ./...